language: haskell

ghc:
  - 7.6.3

before_install:

install:
  - cabal install cabal-install
  - export PATH=$HOME/.cabal/bin:$PATH

  # Showing Cabal configuration
  - cat $HOME/.cabal/config

  # New Happy needed for haskell-src-exts
  - cabal install happy

  # New new Alex for us
  - cabal install alex
  - cabal install cpphs-1.18.9

  - cabal install Agda-2.4.2.2
  - wget https://github.com/agda/agda-stdlib/archive/v0.9.tar.gz -O /tmp/v0.9.tar.gz
  - tar -xzvf /tmp/v0.9.tar.gz -C /tmp/

script:
  - cd agda
  - agda -i . -i /tmp/agda-stdlib-0.9/src/ Everything.agda


notifications:
  email: false

