# Use new container infrastructure to enable caching
sudo: false

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - travis_wait 30 stack install --no-terminal --install-ghc --resolver lts-3.0 Agda
  #- cabal install cabal-install
  #- export PATH=$HOME/.cabal/bin:$PATH

  # Showing Cabal configuration
  #- cat $HOME/.cabal/config

  # New Happy needed for haskell-src-exts
  #- cabal install happy

  # New new Alex for us
  #- cabal install alex
  #- cabal install cpphs-1.18.9

  #- cabal install Agda-2.4.2.2
  # - wget https://github.com/agda/agda-stdlib/archive/v0.9.tar.gz -O /tmp/v0.9.tar.gz
  #- tar -xzf /tmp/v0.9.tar.gz -C /tmp/
  # Agda 2.4.2.5
  - wget https://github.com/agda/agda-stdlib/archive/v0.11.tar.gz -O /tmp/v0.11.tar.gz
  - tar -xzf /tmp/v0.11.tar.gz -C /tmp/
  
script:
  - agda --version
  - agda -i . -i /tmp/agda-stdlib-0.11/src/ Substitution.lagda


notifications:
  email: false

